runtime: java
env: flex
 
runtime_config:
  jdk: openjdk8
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"

handlers:
- url: /.*
  script: mysql “host=10.128.0.11 port=3307 sslmode=disable user=root”

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5 